### ISSUE TITLE
If the current package is incompatible with other packages last release, don't treat this as faillure

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/OscarDevTools.jl#15]
[ We've discussed this before, elsewhere, I just wanted to note it down somewhere for easier reference -- so in particular I do not mean to say "why haven't you done this already" ! ]

Consider this scenario:

- The latest Oscar.jl release has compat 0.6 for GAP.jl
- in the meantime, the latest release of GAP.jl is 0.7, so it can't be loaded in Oscar
- now we run CI tests using OscarDevTools.jl for GAP.jl, which test its master branch against the latest Oscar.jl release
- of course these can't pass, as the latest Oscar.jl is incompatible with GAP.jl master (in fact, something even worse happens: an ancient Oscar.jl version 0.2.0 is installed by Julia.

Ideally, we'd detect this situation: when doing tests for package A against release versions of packages B, C, ..., if the current version of A is not compatible with the latest versions of B, C, ... then don't run any tests and just mark the job as success (after all, there is no incompatibility).

I think the somewhat hard part may be to prevent Julia from downgrading packages B, C, ... to make things work.

**Comment by benlorenz** [comment]
I tried looking into this in https://github.com/oscar-system/OscarDevTools.jl/pull/16 which didn't work as expected but I will give it another try in the next days.

**Comment by benlorenz** [comment]
So I have done a first working version of this in #16 now, but to notice the annotation one has to go to the [`Checks` tab](https://github.com/oscar-system/OscarDevTools.jl/pull/16/checks).
The error is shown [here](https://github.com/oscar-system/OscarDevTools.jl/actions/runs/1805625713) but unfortunately even there github seems to be unable to provide a deeplink to the [corresponding line in the error output](https://github.com/oscar-system/OscarDevTools.jl/runs/5090854730?check_suite_focus=true#step:6:266).

The current approach is to first `add` and `pin` Oscar to the latest release (except if testing some other branch) and then successively add+pin all further packages where no branch is specified. This means that it might not always pick the latest version of other intermediate packages if they are not compatible with the current Oscar release.
And at the end `dev` all packages where a fixed version is requested.
If during all that a `ResolverError` is triggered an annotation is generated and the tests are skipped.

Currently the tests will also be skipped if other parts of the preparation fail (e.g. a random download error or a bug in OscarDevTools). I will try if I can find an easy way to avoid this.
