### ISSUE TITLE
Also run doctests

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/OscarDevTools.jl#17]
We should also run doctests of the involved packages: we just had a case where the regular tests worked, but a PR broke doctests of an upstream project.

One thing to remember for that is that usually our doctests require a specific Julia version; but it should be possible to deal with that (and I think basically Julia 1.6 is currently used for this by all our packages?)

**Comment by thofma** [comment]
What is the julia environment where the following is run:

https://github.com/oscar-system/OscarDevTools.jl/blob/6aa52dadcb4034959074266e7d9eab4deff36e58/src/OscarCI.jl#L283-L297

Is this the environment where all the packages are checked out with the correct version? @benlorenz

**Comment by benlorenz** [comment]
> Is this the environment where all the packages are checked out with the correct version? @benlorenz

This function assembles a long command with multiple `Pkg.test` statements that will be stored in an environment variable to be run in the next actions-step.
It will be executed here:

https://github.com/oscar-system/OscarDevTools.jl/blob/6aa52dadcb4034959074266e7d9eab4deff36e58/.github/workflows/oscar.yml#L88

That `oscar-dev/project` is probably the project you are looking for which contains all packages in the correct versions (except for Documenter).

We could add the doctest command to these `Pkg.test` commands but I think creating an extra step to run the doctests would be cleaner.
